// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type NestedEmptyObject struct {
	Config   map[string]interface{} `json:"config"`
	Metadata map[string]interface{} `json:"metadata"`
	Settings map[string]interface{} `json:"settings"`
}
