// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type Address struct {
	City *string `json:"city"`
}

type Anything any

type Client struct {
	Name *string `json:"name"`
}

type Contacts []Client

type CustomerAlias Client

type Labels []string

type Metadata map[string]interface{}

type Supplier struct {
	Name *string `json:"name"`
}

type UserID string

type Definitions struct {
	Address       Address       `json:"address"`
	Anything      Anything      `json:"anything"`
	Contacts      Contacts      `json:"contacts"`
	Customer      Client        `json:"customer"`
	CustomerAlias CustomerAlias `json:"customer_alias"`
	Labels        Labels        `json:"labels"`
	Metadata      Metadata      `json:"metadata"`
	Supplier      Supplier      `json:"supplier"`
	UserId        UserID        `json:"user_id"`
}
