// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type CustomItemName struct {
	Value *int `json:"value"`
}

type CustomInlineName struct {
	Field *string `json:"field"`
}

type CustomRootName struct {
	ArrayItems []CustomItemName  `json:"array_items"`
	InlineObj  *CustomInlineName `json:"inline_obj"`
}
