package codegen

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/willabides/jsonschematogo/internal/schema"
)

// Options for Go code generation.
type Options struct {
	PackageName string
	// Schemas is a map of URI to *schema.Schema for $ref resolution
	Schemas map[string]*schema.Schema
}

type generator struct {
	seenSignatures map[string]string // signature -> struct name
	file           *jen.File
	opts           Options
}

// GenerateGoCode generates Go code from a parsed schema model and all referenced schemas.
func GenerateGoCode(w io.Writer, sch *schema.Schema, opts *Options) error {
	if opts == nil {
		opts = &Options{PackageName: "gen"}
	}
	if opts.Schemas == nil {
		opts.Schemas = map[string]*schema.Schema{}
	}

	file := jen.NewFile(opts.PackageName)
	file.HeaderComment("Code generated by jsonschematogo. DO NOT EDIT.")

	g := &generator{
		seenSignatures: map[string]string{},
		file:           file,
		opts:           *opts,
	}

	err := g.generateStruct(sch, "")
	if err != nil {
		return fmt.Errorf("generate struct: %w", err)
	}

	return file.Render(w)
}

// generateStruct generates a Go struct for a schema and all referenced/inline schemas.
func (g *generator) generateStruct(sch *schema.Schema, structName string) error {
	signature := structSignature(sch)
	if _, ok := g.seenSignatures[signature]; ok {
		return nil
	}
	if structName == "" {
		var err error
		structName, err = getStructName(sch)
		if err != nil {
			return err
		}
	}
	g.seenSignatures[signature] = structName

	type field struct {
		name string
		stmt *jen.Statement
	}

	var fields []field
	for propName, prop := range sch.OrderedProperties() {
		propExt, err := prop.Extensions()
		if err != nil {
			return err
		}
		refSchema := prop.RefSchema()
		if refSchema != nil {
			err = g.generateStruct(refSchema, "")
			if err != nil {
				return err
			}
		}

		if prop.Type() == "object" && prop.HasProperties() {
			inlineName := structName + capitalizeFirst(propName) + "Object"
			if propExt.GoTypeName != nil {
				inlineName = *propExt.GoTypeName
			}
			err = g.generateStruct(prop, inlineName)
			if err != nil {
				return err
			}
		}

		if prop.Type() == "array" {
			err = g.handleArrayPropertyStructs(prop, structName, propName)
			if err != nil {
				return err
			}
		}
		fieldStmt, err := g.generateField(propName, structName, prop, sch)
		if err != nil {
			return err
		}
		fields = append(fields, field{name: propName, stmt: fieldStmt})
	}

	// Create the struct
	var fieldCodes []jen.Code
	for _, f := range fields {
		fieldCodes = append(fieldCodes, f.stmt)
	}
	structDef := jen.Type().Id(structName).Struct(fieldCodes...)
	g.file.Add(structDef)
	g.file.Line()
	return nil
}

// handleArrayPropertyStructs generates referenced and inline structs for array items.
func (g *generator) handleArrayPropertyStructs(prop *schema.Schema, structName, propName string) error {
	items := prop.Items()
	if items == nil {
		return nil
	}
	refSchema := items.RefSchema()
	if refSchema != nil {
		err := g.generateStruct(refSchema, "")
		if err != nil {
			return err
		}
	}
	if items.Type() == "object" && items.HasProperties() {
		inlineName := structName + capitalizeFirst(propName) + "ItemObject"
		ext, err := items.Extensions()
		if err != nil {
			return err
		}
		if ext.GoTypeName != nil {
			inlineName = *ext.GoTypeName
		}
		err = g.generateStruct(items, inlineName)
		if err != nil {
			return err
		}
	}
	return nil
}

// structSignature returns a string signature for a struct (for deduplication).
func structSignature(sch *schema.Schema) string {
	var fields []string
	props := sch.Properties()
	if props == nil {
		return ""
	}
	for propName, prop := range props {
		ft := prop.Type()
		if prop.Ref() != "" {
			ft = "ref:" + prop.Ref()
		}
		if prop.Type() == "object" && prop.HasProperties() {
			ft = "inline:" + structSignature(prop)
		}
		items := prop.Items()
		if prop.Type() == "array" && items != nil {
			ft = "array:" + structSignature(items)
		}
		fields = append(fields, propName+":"+ft)
	}
	sort.Strings(fields)
	return strings.Join(fields, ";")
}

// generateField generates a Go struct field for a property.
func (g *generator) generateField(name, parentName string, prop, parent *schema.Schema) (*jen.Statement, error) {
	fieldName := toGoFieldName(name)
	ext, err := prop.Extensions()
	if err == nil && ext.GoName != nil {
		fieldName = *ext.GoName
	}
	isRequired := parent.IsPropertyRequired(name)

	typeExpr, err := g.goTypeExpr(prop, parentName, name, isRequired)
	if err != nil {
		return nil, err
	}
	return jen.Id(fieldName).Add(typeExpr).Tag(map[string]string{"json": name}), nil
}

// isBuiltinType checks if a type name is a built-in type.
func isBuiltinType(typeName string) bool {
	switch typeName {
	case "int", "string", "float64", "bool", "any":
		return true
	}
	return false
}

// getXGoTypeExpr handles x-go-type with optional import extensions.
func (g *generator) getXGoTypeExpr(prop *schema.Schema, isRequired bool) (jen.Code, bool, error) {
	ext, err := prop.Extensions()
	if err != nil {
		return nil, false, err
	}
	stmt := &jen.Statement{}
	if ext.GoType == nil {
		return nil, false, nil
	}

	if !isRequired {
		stmt.Op("*")
	}

	typeName := *ext.GoType
	qualPath := ""

	if ext.GoTypeImport != nil {
		parts := strings.Split(typeName, ".")
		typeName = parts[len(parts)-1]
		qualPath = ext.GoTypeImport.Path
		if ext.GoTypeImport.Name != "" && qualPath != "" {
			g.file.ImportAlias(qualPath, ext.GoTypeImport.Name)
		}
	}

	return stmt.Qual(qualPath, typeName), true, nil
}

// getArrayItemExpr handles array item type expressions.
func getArrayItemExpr(items *schema.Schema, parentName, propName string) (jen.Code, error) {
	ext, err := items.Extensions()
	if err != nil {
		return nil, err
	}
	switch {
	case ext.GoType != nil:
		// Check if array items have import extension
		if importPath, _, hasImport := items.GetImportExtension(); hasImport {
			// Extract just the type name from the full qualified name
			typeName := *ext.GoType
			if strings.Contains(*ext.GoType, ".") {
				parts := strings.Split(*ext.GoType, ".")
				typeName = parts[len(parts)-1]
			}
			return jen.Qual(importPath, typeName), nil
		}
		return jen.Id(*ext.GoType), nil
	case items.Ref() != "":
		return jen.Id(refTypeName(items.Ref())), nil
	case items.Type() == "object" && items.HasProperties():
		inlineName := parentName + capitalizeFirst(propName) + "ItemObject"
		if ext.GoTypeName != nil {
			inlineName = *ext.GoTypeName
		}
		return jen.Id(inlineName), nil
	case items.Type() == "object":
		return jen.Map(jen.String()).Interface(), nil
	default:
		return jen.Id(getPrimitiveGoType(items.Type())), nil
	}
}

// goTypeExpr builds a jen.Code type expression for a schema property.
func (g *generator) goTypeExpr(prop *schema.Schema, parentName, propName string, isRequired bool) (jen.Code, error) {
	// Handle x-go-type first
	expr, ok, err := g.getXGoTypeExpr(prop, isRequired)
	if err != nil {
		return nil, err
	}
	if ok {
		return expr, nil
	}

	if prop.Ref() != "" {
		refName := refTypeName(prop.Ref())
		if !isRequired {
			return jen.Op("*").Id(refName), nil
		}
		return jen.Id(refName), nil
	}

	if prop.Type() == "array" {
		items := prop.Items()
		if items == nil {
			return jen.Index().Interface(), nil
		}
		var itemExpr jen.Code
		itemExpr, err = getArrayItemExpr(items, parentName, propName)
		if err != nil {
			return nil, err
		}
		return jen.Index().Add(itemExpr), nil
	}

	if prop.Type() == "object" {
		return g.goTypeObjectExpr(prop, parentName, propName, isRequired)
	}

	typeName := getPrimitiveGoType(prop.Type())
	if !isRequired && !isSliceOrMapType(typeName) {
		if isBuiltinType(typeName) {
			return jen.Id("*" + typeName), nil
		}
		return jen.Op("*").Id(typeName), nil
	}
	return jen.Id(typeName), nil
}

func (g *generator) goTypeObjectExpr(
	prop *schema.Schema,
	parentName, propName string,
	isRequired bool,
) (jen.Code, error) {
	if !prop.HasProperties() {
		return jen.Map(jen.String()).Interface(), nil
	}
	inlineName := parentName + capitalizeFirst(propName) + "Object"
	ext, err := prop.Extensions()
	if err != nil {
		return nil, err
	}
	if ext.GoTypeName != nil {
		inlineName = *ext.GoTypeName
	}
	if !isRequired {
		return jen.Op("*").Id(inlineName), nil
	}
	return jen.Id(inlineName), nil
}

func refTypeName(ref string) string {
	parts := strings.Split(ref, "/")
	if len(parts) > 0 {
		name := parts[len(parts)-1]
		name = strings.TrimSuffix(name, ".yaml")
		name = strings.TrimSuffix(name, ".yml")
		name = strings.TrimSuffix(name, ".json")
		return capitalizeFirst(name)
	}
	return "any"
}

// getStructName gets the struct name from x-go-type-name, x-go-type extension or infers it.
func getStructName(sch *schema.Schema) (string, error) {
	ext, err := sch.Extensions()
	if err != nil {
		return "", err
	}
	if ext.GoTypeName != nil {
		return *ext.GoTypeName, nil
	}
	if ext.GoType != nil {
		return *ext.GoType, nil
	}

	// Infer from location or use a default
	if sch.Location() != "" {
		// Extract name from file path
		loc, _, _ := strings.Cut(sch.Location(), "#")
		parts := strings.Split(loc, "/")
		if len(parts) > 0 {
			name := parts[len(parts)-1]
			name = strings.TrimSuffix(name, ".yaml")
			name = strings.TrimSuffix(name, ".yml")
			name = strings.TrimSuffix(name, ".json")
			return capitalizeFirst(name), nil
		}
	}

	return "Object", nil
}

// getPrimitiveGoType maps JSON Schema primitive types to Go types.
func getPrimitiveGoType(jsonType string) string {
	switch jsonType {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "null":
		return "any"
	default:
		return "any"
	}
}

// capitalizeFirst capitalizes the first letter of a string.
func capitalizeFirst(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// toGoFieldName converts a JSON Schema property name to an idiomatic Go field name.
func toGoFieldName(s string) string {
	if s == "" {
		return ""
	}

	// Split by underscores and capitalize each part
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = capitalizeFirst(part)
	}

	return strings.Join(parts, "")
}

// isSliceOrMapType checks if a Go type is a slice or map.
func isSliceOrMapType(goType string) bool {
	return strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[")
}
