// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type FieldNamingEdgeCases struct {
	UPPERCASEFIELD      *string `json:"UPPER_CASE_FIELD"`
	PrivateField        *string `json:"_private_field"`
	ApiKey              *string `json:"api_key"`
	CamelCaseField      *string `json:"camelCaseField"`
	CreatedAt           *string `json:"created_at"`
	FieldWith123Numbers *string `json:"field_with_123_numbers"`
	FieldWithDash       *string `json:"field_with_dash"`
	FieldWithDot        *string `json:"field_with_dot"`
	HttpStatusCode      *int    `json:"http_status_code"`
	IsActive            *bool   `json:"is_active"`
	UpdatedAt           *string `json:"updated_at"`
	UserId              *string `json:"user_id"`
}
