// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type LegacyId int

type LegacyObject struct {
	Value *string `json:"value"`
}

type LegacyDefinitions struct {
	Id     LegacyId     `json:"id"`
	Object LegacyObject `json:"object"`
}
