// Code generated by jsonschematogo. DO NOT EDIT.

package gen

import (
	googleuuid "github.com/google/uuid"
	"time"
)

type ImportTestSettingsObject struct {
	MaxItems *MaxItems `json:"max_items"`
	Theme    *Theme    `json:"theme"`
}

type ImportTest struct {
	CreatedAt *time.Time                `json:"created_at"`
	Settings  *ImportTestSettingsObject `json:"settings"`
	Tags      []googleuuid.UUID         `json:"tags"`
	UserId    *googleuuid.UUID          `json:"user_id"`
}
