// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type NestedGoTypeMetadataObject struct {
	CreatedAt *string `json:"created_at"`
	Tags      []Tag   `json:"tags"`
}

type NestedGoTypeSettingsObject struct {
	Notifications *bool   `json:"notifications"`
	Theme         *string `json:"theme"`
}

type NestedGoTypeUserObject struct {
	Email *EmailAddress `json:"email"`
	Id    *int          `json:"id"`
	Name  *string       `json:"name"`
}

type NestedGoType struct {
	Metadata *Metadata     `json:"metadata"`
	Settings *UserSettings `json:"settings"`
	User     *User         `json:"user"`
}
