// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type XGoNameTest struct {
	APIKeyOverride *string `json:"api_key"`
	NormalField    *string `json:"normal_field"`
	UserIDOverride *string `json:"user_id"`
}
