// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type ArrayGoTypesSettings_mapItemObject struct {
	Key   *string `json:"key"`
	Value *string `json:"value"`
}

type ArrayGoTypesUser_listItemObject struct {
	Id   *int    `json:"id"`
	Name *string `json:"name"`
}

type ArrayGoTypes struct {
	EmailAddresses []EmailAddress `json:"email_addresses"`
	SettingsMap    *SettingsList  `json:"settings_map"`
	UserIds        []UserID       `json:"user_ids"`
	UserList       *UserList      `json:"user_list"`
}
