// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type OptionalPropertiesOptional_objectObject struct {
	Name *string `json:"name"`
}

type OptionalProperties struct {
	OptionalBool   *bool                                    `json:"optional_bool"`
	OptionalInt    *int                                     `json:"optional_int"`
	OptionalObject *OptionalPropertiesOptional_objectObject `json:"optional_object"`
	OptionalString *string                                  `json:"optional_string"`
	RequiredBool   bool                                     `json:"required_bool"`
	RequiredInt    int                                      `json:"required_int"`
	RequiredObject OptionalPropertiesRequired_objectObject  `json:"required_object"`
	RequiredString string                                   `json:"required_string"`
}
