// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type SchemaDraft2019ItemsItemObject struct {
	Id    *string  `json:"id"`
	Value *float64 `json:"value"`
}

type SchemaDraft2019 struct {
	Age    *int                             `json:"age"`
	Email  *string                          `json:"email"`
	Flags  []bool                           `json:"flags"`
	Items  []SchemaDraft2019ItemsItemObject `json:"items"`
	Name   *string                          `json:"name"`
	Scores []float64                        `json:"scores"`
	Tags   []string                         `json:"tags"`
}
