// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type Person struct {
	Age   *int    `json:"age"`
	Email *string `json:"email"`
	Name  *string `json:"name"`
}

type Company struct {
	Ceo       Person   `json:"ceo"`
	Employees []Person `json:"employees"`
	Founded   int      `json:"founded"`
	Name      string   `json:"name"`
}
