// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type ArrayOfPrimitives struct {
	Bools   []bool    `json:"bools"`
	Floats  []float64 `json:"floats"`
	Ints    []int     `json:"ints"`
	Strings []string  `json:"strings"`
}
