// Code generated by jsonschematogo. DO NOT EDIT.

package gen

import (
	uuid "github.com/google/uuid"
	"time"
)

type ExtensionEdgeCases struct {
	WithImportEmptyName *time.Time `json:"with_import_empty_name"`
	WithImportEmptyPath *Type      `json:"with_import_empty_path"`
	WithImportNoName    *time.Time `json:"with_import_no_name"`
	WithImportWithName  *uuid.UUID `json:"with_import_with_name"`
}
