// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type Primitives struct {
	ABool   *bool    `json:"a_bool"`
	AFloat  *float64 `json:"a_float"`
	ANull   *any     `json:"a_null"`
	AString *string  `json:"a_string"`
	AnInt   *int     `json:"an_int"`
}
