#!/bin/sh
#/ script/jsonschematogo builds and runs the project with the given arguments.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

go build -o bin/jsonschematogo ./cmd/jsonschematogo

exec bin/jsonschematogo "$@"
