// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type ArrayWithRefItemsDepartmentsItemObject struct {
	Location *string `json:"location"`
	Name     *string `json:"name"`
}

type ArrayWithRefItemsMetadataItemObject struct {
	Key   *string `json:"key"`
	Value *string `json:"value"`
}

type ArrayWithRefItemsUsersItemObject struct {
	Email *string `json:"email"`
	Id    *string `json:"id"`
	Name  *string `json:"name"`
}

type ArrayWithRefItems struct {
	Departments []ArrayWithRefItemsDepartmentsItemObject `json:"departments"`
	Metadata    []ArrayWithRefItemsMetadataItemObject    `json:"metadata"`
	Tags        []string                                 `json:"tags"`
	Users       []ArrayWithRefItemsUsersItemObject       `json:"users"`
}
