// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type InlineObjectMetaObject struct {
	Timestamp *int    `json:"timestamp"`
	Version   *string `json:"version"`
}

type InlineObject struct {
	Meta *InlineObjectMetaObject `json:"meta"`
}
