// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type ObjectWithNoProperties struct {
	AnotherEmpty map[string]interface{} `json:"another_empty"`
	Config       map[string]interface{} `json:"config"`
	EmptyObject  map[string]interface{} `json:"empty_object"`
	Settings     map[string]interface{} `json:"settings"`
}
