// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type MultipleEnums struct {
	Category *string `json:"category"`
	Priority *string `json:"priority"`
	Severity *int    `json:"severity"`
	State    *string `json:"state"`
	Status   *string `json:"status"`
	Type     *string `json:"type"`
}
