// Code generated by jsonschematogo. DO NOT EDIT.

package gen

import (
	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	time "time"
)

type ComplexXGoTypeImportArray_with_importsItemObject struct {
	CreatedAt *time.Time `json:"created_at"`
	Id        *uuid.UUID `json:"id"`
}

type ComplexXGoTypeImportNested_with_importObject struct {
	Amount    *decimal.Decimal `json:"amount"`
	Timestamp *time.Time       `json:"timestamp"`
}

type ComplexXGoTypeImport struct {
	ArrayWithImports []ComplexXGoTypeImportArray_with_importsItemObject `json:"array_with_imports"`
	DecimalField     *decimal.Decimal                                   `json:"decimal_field"`
	DurationField    *time.Duration                                     `json:"duration_field"`
	NestedWithImport *ComplexXGoTypeImportNested_with_importObject      `json:"nested_with_import"`
	TimeField        *time.Time                                         `json:"time_field"`
	UuidField        *uuid.UUID                                         `json:"uuid_field"`
}
