// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type PrimitiveGoTypesSettingsObject struct {
	MaxItems *MaxItems `json:"max_items"`
	Theme    *Theme    `json:"theme"`
}

type PrimitiveGoTypes struct {
	CreatedAt *Timestamp    `json:"created_at"`
	Email     *EmailAddress `json:"email"`
	IsActive  *ActiveStatus `json:"is_active"`
	Score     *Score        `json:"score"`
	Settings  *Settings     `json:"settings"`
	Tags      []Tag         `json:"tags"`
	UserId    *UserID       `json:"user_id"`
}
