// Code generated by jsonschematogo. DO NOT EDIT.

package gen

type ComplexNestingOrganizationObjectDepartmentsItemObjectEmployeesItemObject struct {
	Id   *string `json:"id"`
	Role *string `json:"role"`
}

type ComplexNestingOrganizationObjectDepartmentsItemObject struct {
	Employees []ComplexNestingOrganizationObjectDepartmentsItemObjectEmployeesItemObject `json:"employees"`
	Name      *string                                                                    `json:"name"`
}

type ComplexNestingOrganizationObject struct {
	Departments []ComplexNestingOrganizationObjectDepartmentsItemObject `json:"departments"`
}

type ComplexNestingUserObjectProfileObjectPersonalObjectPreferencesObjectNotificationsObject struct {
	Email *bool `json:"email"`
	Push  *bool `json:"push"`
	Sms   *bool `json:"sms"`
}

type ComplexNestingUserObjectProfileObjectPersonalObjectPreferencesObject struct {
	Notifications *ComplexNestingUserObjectProfileObjectPersonalObjectPreferencesObjectNotificationsObject `json:"notifications"`
	Theme         *string                                                                                  `json:"theme"`
}

type ComplexNestingUserObjectProfileObjectPersonalObject struct {
	Age         *int                                                                  `json:"age"`
	Name        *string                                                               `json:"name"`
	Preferences *ComplexNestingUserObjectProfileObjectPersonalObjectPreferencesObject `json:"preferences"`
}

type ComplexNestingUserObjectProfileObject struct {
	Personal *ComplexNestingUserObjectProfileObjectPersonalObject `json:"personal"`
}

type ComplexNestingUserObject struct {
	Profile *ComplexNestingUserObjectProfileObject `json:"profile"`
}

type ComplexNesting struct {
	Organization *ComplexNestingOrganizationObject `json:"organization"`
	User         *ComplexNestingUserObject         `json:"user"`
}
